### ISSUE TITLE
Loading Tox Profiles

### ISSUE THREAD

**Issue by CaptainKraft** [haavard/tox-weechat#10]
Loading a Tox profile that was created via a different client doesn't work for me. If this isn't meant to be a feature, it would be nice to add.

**Comment by haavardp** [comment]
Thank you for reporting. I'll take a look at this as time permits; in the meantime, could you provide the versions of your WeeChat, libtoxcore, and from which other client you can't load profiles? Any error messages could be useful as well. Thanks!

**Comment by CaptainKraft** [comment]
My weechat is 1.5-2 and libtoxcore is 3747-2 according to the Arch Linux package repository. Looking in qTox tells me the version of my toxcore is 0.0.0

I have a profile that was created by qTox and that I regularly use with Toxic which would not load.

**Comment by haavard** [comment]
Hi, I am not able to reproduce this on the latest master branch. I am able to load profiles created with both Toxic and qTox, both password-protected and not. Could you please check if the latest version works for you?

**Comment by CaptainKraft** [comment]
Sorry about that, I forgot to close this issue. My toxcore and Toxic versions were out of sync. Now that everything is updated, the problem was fixed.
