### ISSUE TITLE
Tox libraries are not linked properly to tox.so

### ISSUE THREAD

**Issue by gordon-quad** [haavard/tox-weechat#17]
After commit 1cc1aa2a2f2048c19ef04b95fec687bfed03fc91 make produced tox.so which is not linked to libtoxav.so and libtoxencryptsave.so which leads to inability to load tox.so in weechat:
```
unable to load plugin "/home/gordon/.weechat/plugins/tox.so": /home/gordon/.weechat/plugins/tox.so: undefined symbol: tox_pass_encrypt
```
I am using c-toxcore from git and it seems that it never produced single libtoxcore.so with everything linked inside. I wonder why did you change FindTox.cmake to exclude those libraries from Tox_LIBRARIES cmake variable?

**Comment by gordon-quad** [comment]
After i did the following fix  78b0621a110a6b612b9394384c23a52cfb49381e it works for me now

**Comment by haavard** [comment]
That's my bad -- I assumed the newer version of toxcore built a monolithic shared object, but it looks like it depends on whether or not toxcore is built with cmake or autotools. Our CMake find module for Tox will have to work for both of these situations.

**Comment by gordon-quad** [comment]
FYI Toktok/c-toxcore#869

**Comment by gordon-quad** [comment]
According to conversation in IRC cmake is preferred way of building toxcore and autotools script needs updating, so I suppose its time to fix gentoo ebuilds and get single libtoxcore.so.

But since they are not going to fix autotools script soon it still would be nice to support both monolithic and split versions in FindTox.cmake if it will not be too difficult to implement.

**Comment by haavard** [comment]
Should be fixed in the commit above.
